minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  #  application:
  #    name: MyHome
  datasource:
    url: jdbc:mysql://localhost:3306/local_file?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: shan
    password: shan
  redis:
    database: 0
    host: 192.168.218.131
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
